# fly.toml - Configuração para deploy da SafeEdu API
# WorldSkills 2025 - Módulo A2 - Desenvolvimento de Aplicativos
# Deploy no Fly.io

# =============================================================================
# CONFIGURAÇÕES BÁSICAS DA APLICAÇÃO
# =============================================================================

# Nome da aplicação (deve ser único no Fly.io)
app = "bibliotech-api"
primary_region = "gru"  # São Paulo, Brasil (mais próximo)
kill_signal = "SIGINT"
kill_timeout = "5s"

# =============================================================================
# CONFIGURAÇÕES DE BUILD
# =============================================================================

[build]
  # Usar Dockerfile para build
  dockerfile = "Dockerfile"
  
  # Ignorar arquivos durante build
  ignorefile = ".dockerignore"

# =============================================================================
# VARIÁVEIS DE AMBIENTE
# =============================================================================

[env]
  # Configurações da aplicação
  PORT = "8080"
  HOST = "0.0.0.0"
  ENVIRONMENT = "production"
  
  # Identificação da API
  API_NAME = "SafeEdu"
  COMPANY = "SafeEdu"
  
  # Configurações de log
  LOG_LEVEL = "info"
  
  # Timezone
  TZ = "America/Fortaleza"
  
  # Configurações específicas da API
  API_VERSION = "1.0.0"
  MAX_UPLOAD_SIZE = "5242880"  # 5MB em bytes
  
  # CORS settings
  CORS_ORIGIN = "*"
  CORS_METHODS = "GET,POST,PUT,DELETE,OPTIONS"
  
  # WorldSkills settings
  WORLDSKILLS_MODULE = "A2"
  WORLDSKILLS_VARIANT = "safeedu"

# =============================================================================
# SERVIÇOS HTTP
# =============================================================================

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  
  # Configurações de concorrência
  [services.concurrency]
    type = "connections"
    hard_limit = 50      # Máximo de conexões simultâneas
    soft_limit = 40      # Limite suave para auto-scaling
    
  # Configurações de ports externos
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true   # Redirecionar HTTP para HTTPS
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    
  # =============================================================================
  # HEALTH CHECKS
  # =============================================================================
  
  # TCP Check - Verificação básica de conectividade
  [[services.tcp_checks]]
    interval = "15s"      # Verificar a cada 15 segundos
    timeout = "2s"        # Timeout de 2 segundos
    grace_period = "10s"  # Período de graça após deploy
    restart_limit = 0     # Não reiniciar automaticamente por TCP check
    
  # HTTP Check - Verificação do endpoint de saúde
  [[services.http_checks]]
    interval = "30s"           # Verificar a cada 30 segundos
    timeout = "5s"             # Timeout de 5 segundos
    grace_period = "20s"       # Período de graça após deploy
    restart_limit = 0          # Não reiniciar automaticamente
    method = "GET"             # Método HTTP
    path = "/health"           # Endpoint de health check
    protocol = "http"          # Protocolo
    tls_skip_verify = false    # Verificar certificado TLS
    
    # Headers para o health check
    [services.http_checks.headers]
      User-Agent = "Fly-Health-Check"
      Accept = "application/json"

# =============================================================================
# VOLUMES (ARMAZENAMENTO PERSISTENTE)
# =============================================================================

[mounts]
  # Volume para uploads de arquivos (mantendo nome existente)
  source = "bibliotech_uploads"
  destination = "/app/uploads"
  initial_size = "1gb"        # Tamanho inicial de 1GB
  
# =============================================================================
# CONFIGURAÇÕES DE DEPLOY
# =============================================================================

[deploy]
  # Estratégia de deploy
  strategy = "rolling"        # Deploy gradual (sem downtime)
  
# =============================================================================
# MÉTRICAS E MONITORING
# =============================================================================

[metrics]
  # Habilitar métricas do Fly.io
  port = 9091
  path = "/metrics"

# =============================================================================
# CONFIGURAÇÕES DE REGIÃO E SCALING
# =============================================================================

# Configurações de auto-scaling otimizadas com auto-stop
[scaling]
  min_machines_running = 0    # Permite parar todas as máquinas (economia)
  max_machines_running = 3    # Máximo de 3 instâncias (para alta demanda)

# =============================================================================
# AUTO STOP - ECONOMIA DE RECURSOS
# =============================================================================

# Configuração de auto-stop com timeout de 3 horas
[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
# Configuração de timeout para parar máquinas automaticamente
[auto_stop_machines]
  # Parar máquinas após 3 horas de inatividade (10800 segundos)
  timeout = "3h"

# =============================================================================
# CONFIGURAÇÕES ESPECÍFICAS DA SAFEEDU API
# =============================================================================

# =============================================================================
# CONFIGURAÇÕES DE RECURSOS
# =============================================================================

# Configurações de CPU e memória (simplificadas)
[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1